// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingAnalyticsLab.Infrastructure.Persistence;

#nullable disable

namespace TradingAnalyticsLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingAnalyticsLabDbContext))]
    [Migration("20260603155106_AddAuditFieldsToTradingAccount")]
    partial class AddAuditFieldsToTradingAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntryId");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossResult")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetResult")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SetupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TradingSessionSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("TradeId");

                    b.HasIndex("TradingSessionSessionId");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.Trader", b =>
                {
                    b.Property<Guid>("TraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TraderId");

                    b.ToTable("traders", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.TradingAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.ToTable("trading_accounts", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.TradingSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.ToTable("trading_sessions", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.TradingSetup", b =>
                {
                    b.Property<Guid>("SetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SetupId");

                    b.ToTable("trading_setups", (string)null);
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.Trade", b =>
                {
                    b.HasOne("TradingAnalyticsLab.Domain.Entities.TradingSession", null)
                        .WithMany("Trades")
                        .HasForeignKey("TradingSessionSessionId");
                });

            modelBuilder.Entity("TradingAnalyticsLab.Domain.Entities.TradingSession", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
